services:
  postgres_db:
    image: postgres:15-alpine
    container_name: phoenix_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: forensic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forensic_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: phoenix_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@phoenix.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - forensic_network

  qdrant_db:
    image: qdrant/qdrant:latest
    container_name: phoenix_qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - forensic_network

  ai-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: phoenix_ai_core
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models_weights:/app/models_weights
      - ./cloud_storage:/app/cloud_storage
      - torch_cache:/root/.cache
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 --limit-concurrency 8 --timeout-keep-alive 5
    depends_on:
      - postgres_db
      - qdrant_db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://admin:supersecretpassword@postgres_db:5432/forensic_db
      QDRANT_URL: http://qdrant_db:6333
    mem_limit: 3g
    mem_reservation: 2g
    shm_size: 1g
    networks:
      - forensic_network

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: phoenix_gateway
    ports:
      - "8080:8080"
    environment:
      AI_BACKEND_URL: http://phoenix_ai_core:8000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/forensic_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: supersecretpassword
    depends_on:
      - ai-backend
      - postgres_db
    networks:
      - forensic_network

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: phoenix_dashboard
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - api-gateway
    networks:
      - forensic_network

volumes:
  postgres_data:
  pgadmin_data:
  qdrant_data:
  torch_cache:

networks:
  forensic_network:
    driver: bridge
